"""Render the human readable third party resource manifest from its data source."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

SOURCE = "docs/licenses/third-party-resources.yaml"
TARGET = "docs/licenses/THIRD_PARTY_RESOURCES.md"

FIELDS = (
    "name",
    "source",
    "version",
    "license",
    "license_url",
    "purpose",
    "integration_location",
    "modification_status",
    "redistribution_requirements",
    "attribution_requirements",
    "checksum_manifest",
)


def render(repo: Path) -> str:
    payload = yaml.safe_load((repo / SOURCE).read_text(encoding="utf-8"))
    lines = [
        "# Third Party Resources",
        "",
        "Every external resource used by the project is recorded here. The machine readable source of truth is `docs/licenses/third-party-resources.yaml`.",
        "",
        "| Field | Value |",
        "| --- | --- |",
    ]
    for resource in payload["resources"]:
        lines.append(f"| Resource | {resource['name']} |")
        for field in FIELDS:
            if field == "name":
                continue
            lines.append(f"| {field.replace('_', ' ')} | {resource.get(field, 'not-recorded')} |")
        lines.append("| --- | --- |")
    lines.append("")
    lines.append("Generated by tools/license/render_manifest.py. Do not edit manually.")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Render the third party resource manifest")
    parser.add_argument("--repo", default=".")
    parser.add_argument("--check", action="store_true", help="verify that the rendered document is current without writing")
    arguments = parser.parse_args()
    repo = Path(arguments.repo).resolve()
    output = render(repo)
    target = repo / TARGET
    if arguments.check:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current != output:
            print(f"render_manifest status=FAIL {TARGET} is out of date, run the renderer without --check")
            return 1
        print(f"render_manifest status=PASS {TARGET} is current with {output.count('| Resource |')} resources")
        return 0
    target.write_text(output, encoding="utf-8")
    print(f"rendered {TARGET} with {output.count('| Resource |')} resources")
    return 0


if __name__ == "__main__":
    sys.exit(main())
